### ISSUE TITLE
Error - cache limiter

### ISSUE THREAD

**Issue by Bayerberg** [anaggh/Bludit-Search#2]
I'm getting this: 

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /local_server/lublin-city/search.php:47) in /local_server/lublin-city/bl-kernel/helpers/session.class.php on line 40

Not sure how to solve this

**Comment by anaggh** [comment]
No idea either. It was reported last time  #1 I was not able to reproduce. Which PHP version are you running? Maybe you could try adding `<?php session_start(); ?>` at the top of search.php. If possible could you zip the bludit installation and send it to me? anagghscm [at] gmail.com ?

**Comment by Bayerberg** [comment]
wow, that did the trick. 
bludit 1.6.2, tweaked a bit already, thought I messed something up :) 
thanks!
