### ISSUE TITLE
Error 500 on live

### ISSUE THREAD

**Issue by Bayerberg** [anaggh/Bludit-Search#4]
Weird error - I get error 500 on live server while having no problems on local host. only one thin that changed is the URL.

**Comment by anaggh** [comment]
Please provide logs.

**Comment by anaggh** [comment]
Hey, did you manage to fix this?

**Comment by Bayerberg** [comment]
yes, don't remember how though :) will check and get back to you

**Comment by anaggh** [comment]
Okay, closing this.

**Comment by Yoneo** [comment]
For me it has helped to remove the #-Symbol before the Line with the RewriteBase.

```
# Base directory
(#) RewriteBase /

```
